### ISSUE TITLE
Different imputed values for the same observation

### ISSUE THREAD

**Issue by statunizaga** [FarrellDay/miceRanger#12]
Hi, im gonna show you what i was talking about.
Try this:
require(miceRanger)
require(dplyr)

# Creating 2 data sets with the same observation
data(iris)
set.seed(1)
ampIris <- amputeData(iris,perc=0.25)

ampIris$id <- 1:150
miceObj <- miceRanger(ampIris,verbose=FALSE,returnModels = TRUE)
set.seed(1)
i1 = impute(ampIris,miceObj)

set.seed(1)
ampIris2 <- ampIris %>% filter(id==1) %>% 
  bind_rows(ampIris %>% filter(id!=1) %>% head(15))
i2 = impute(ampIris2,miceObj)

# Selecting the id =1
ampIris %>% 
  filter(id==1)

i1$imputedData$Dataset_3 %>% 
  filter(id==1)

i2$imputedData$Dataset_3 %>% 
  filter(id==1)

you can see that for the same observation has different imputed values in petal.length and even setting the seed.

**Comment by samFarrellDay** [comment]
Sorry for the late reply, my company just changed up tenants and I wasn't getting notifications for issues for a while.

The seed only ensures that the same results are produced if the same process is run. It does not ensure that the same value will imputed for the same sample, if the sample is a part of two different processes. In your example, you are imputing a different dataset the second time - one that only has 16 rows. Although, this idea is an interesting one... I need to think about if I could add this functionality.
