### ISSUE TITLE
training mice ranger on a complete dataset

### ISSUE THREAD

**Issue by robertocerinaprojects** [FarrellDay/miceRanger#18]
I was wondering if it is possible to train miceRanger on a complete dataset. 

I am looking to use this to learn the joint distribution of the underlying data, and use the results as a sort of "generative" model, where one could simulate different "fake" datasets. 

So far I'm doing this by randomly generating missing values in my original training set, and training miceRanger on this synthetically incomplete dataset. But having to generate random missingness adds unnecessary complexity. 

Do you have any advice on the matter ? 

Thanks, 
Roberto

**Comment by samFarrellDay** [comment]
Generating models on columns with complete data is not included in this package. It is included in the python version of this package, [miceforest](https://github.com/AnotherSamWilson/miceforest), however this feature is still rather experimental.

One hacky way around this would be to create 1 row with all missing data. That way the row is not used in training of any of the models, but it forces a model to be trained.
