### ISSUE TITLE
plotDistributions() and 

### ISSUE THREAD

**Issue by tsatsatsa** [FarrellDay/miceRanger#5]
Dear author, I'm using your package and I found it an awsome implementation of mice with Ranger. 

I was able to impute a data frame of 160000 obs and 14 variables (all numeric) with success. 
Unfortunately 3 functions of the package are throwing me an error:

1) plotDistributions()
> >plotDistributions(miceObj)
> Error in get(var) : object 'Cond' not found

plotDistribution is not finding the 'Cond' variable (or any other imputed variable) in the miceObj. I also try to run plotDistributions(miceObj, vars='Cond') (or any other imputed variable) to only plot a one of them without success. 

2) plotImputationVariance()
> > plotImputationVariance(miceObj)
> Error in get(v) : object 'ConduScm' not found

Same problem as for plotDistributions()

3) completeData()

> > dataList <- completeData(miceObj)
>  Error in `:=`((v), miceObj$finalImps[[x]][[v]]) : 
>    Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").

I'm using the last version of the package uploaded on github and I successfully used these functions with the iris data. Conversely, I can not find a way to get the 3 functions work with my dataset.
Any help is much appreciated! Thank you

![Capture](https://user-images.githubusercontent.com/32352578/78296707-834c9100-752e-11ea-9550-fa9b71732bcb.JPG)

**Comment by samFarrellDay** [comment]
Interesting, can you post the output of sessionInfo(). Also, is there any way you can make this reproducible by putting the data and code somewhere? I don't get this error in any unit tests, and I thought they were pretty comprehensive.

**Comment by tsatsatsa** [comment]
I've uploaded code, workspace and rawdata here: https://drive.switch.ch/index.php/s/gJY23cvnspJZ690

The vignettes are extremely comprehensive and detailed. I'm really not able to reproduce the error with commonly used test data and I do not see a difference in terms of output between what I get with the Iris data and my data.

I cleaned the code a bit to just compare the iris data with my data and I also added the package list to the workspace. When I installed miceRanger from github I had to update a list of 10+ packages and they might not be the same version as yours?

**Comment by samFarrellDay** [comment]
Thanks, this is caused by the fact that the raw data saved in the `miceDefs `object isn't cast to a data.table. Pretty much all data manipulations in the package use data.table syntax, so this error will occur any time a data.frame is passed. A pretty big oversight. I'll fix this today, for now, you can avoid the errors by using `setDT()` on your data before running `miceRanger()`.

**Comment by tsatsatsa** [comment]
Many thanks! It is working as intended now!
